image_parameters:
  height_og: 528
  p1:
  - 81
  - 812
  p2:
  - 51
  - 332
  p3:
  - 447
  - 808
  p4:
  - 308
  - 393
  px:
  - 220
  - 381
  py:
  - 76
  - 476
  pz:
  - 68
  - 336
  size_frame: '640'
  width_og: 935
