image_parameters:
  height_og: 640
  p1:
  - 146
  - 309
  p2:
  - 195
  - 158
  p3:
  - 593
  - 287
  p4:
  - 504
  - 166
  px:
  - 389
  - 271
  py:
  - 312
  - 257
  pz:
  - 305
  - 289
  size_frame: '640'
  width_og: 352
