image_parameters:
  height_og: 1280
  p1:
  - 531
  - 344
  p2:
  - 217
  - 335
  p3:
  - 977
  - 484
  p4:
  - 565
  - 554
  px:
  - 646
  - 545
  py:
  - 499
  - 509
  pz:
  - 565
  - 558
  size_frame: '320'
  width_og: 720
